version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - yarn install --lock-file
      # - yarn ci:lint
      # - yarn typecheck
  build:
    commands:
      - yarn build
    
  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://Task1-API
      - aws cloudfront create-invalidation --distribution-id E2HEJI1TEBC93P --paths /index.js
      