version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - yarn install --frozen-lockfile
  pre_build:
    commands:
      - yarn ci:lint
      - yarn typecheck
  build:
    commands:
      - yarn build
    
  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://task1-API
      - aws cloudfront create-invalidation --distribution-id